apotek/urls.py
from django.contrib import admin
from django.urls import path
from apotek import views

app_name = 'apotek'
urlpatterns = [
    path('', views.list_apotek, name ='list_apotek'),
    path('produk/', views.list_produk_apotek, name ='list_produk_apotek'),
    path('delete/<id>', views.delete_apotek, name ='delete_apotek'),
    path('produk/delete/<id_apotek>/<id_produk>', views.delete_produk_apotek, name ='delete_produk_apotek'),
    path('update/<id>', views.update_apotek, name ='to_update_apotek'),
    path('produk/update/<id_apotek>/<id_produk>', views.update_produk_apotek,
         name ='to_update_produk_apotek'),
    path('create/', views.create_apotek, name ='create_apotek'),
    path('produk/create/', views.create_produk_apotek, name ='create_produk_apotek'),
    path('produk/avlble/<id>', views.id_produk_choices, name = 'id_produk_choice')
]

tk_basdat_43/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('login_register.urls')),
    path('transaksi_pembelian/', include('transaksi_pembelian.urls')),
    path('list_produk_pengantaran/',include('list_produk_pengantaran.urls', namespace = 'list_produk_pengantaran')),
    path('balai_pengobatan/', include('balai_pengobatan.urls')),
    path('apotek/', include('apotek.urls')),
]

apotek/models.py
from django.db import models

# Create your models here.

apotek/forms.py
from django import forms
import re

class UpdateApotekForm(forms.Form):
    id_apotek = forms.CharField(max_length=10, required=True)
    nama_apotek = forms.CharField(max_length=50, required=True)
    alamat_apotek = forms.CharField(required=True)
    telepon_apotek = forms.CharField(max_length=20, required=True)
    nama_penyelenggara = forms.CharField(max_length=50, required=True)
    no_sia = forms.CharField(max_length=20, required=True)
    email = forms.EmailField(max_length=50, required=True)

    def clean(self):
        cd = self.cleaned_data
        id_apotek = cd.get("id_apotek")
        nama_apotek = cd.get("nama_apotek")
        alamat_apotek = cd.get("alamat_apotek")
        telepon_apotek = cd.get("telepon_apotek")
        nama_penyelenggara = cd.get("nama_penyelenggara")
        no_sia = cd.get("no_sia")
        email = cd.get("email")

        if re.search('[\D]', str(id_apotek)):
            self.add_error("id_apotek", "id_apotek contains Non-Digit character")

        if re.search('[\D]', str(no_sia)):
            self.add_error('no_sia', "No SIA contains Non-Digit character")

        if not bool(re.search('^\d{3} \d{3} \d{4}$', str(telepon_apotek))):
            self.add_error("telepon_apotek", "Wrong No Telp Apotek Format {XXX - XXX - XXXX}")

        return cd


class CreateApotekForm(forms.Form):
    nama_apotek = forms.CharField(max_length=50, required=True)
    alamat_apotek = forms.CharField(required=True)
    telepon_apotek = forms.CharField(max_length=20, required=True)
    nama_penyelenggara = forms.CharField(max_length=50, required=True)
    no_sia = forms.CharField(max_length=20, required=True)
    email = forms.EmailField(max_length=50, required=True)

    def clean(self):
        cd = self.cleaned_data
        nama_apotek = cd.get("nama_apotek")
        alamat_apotek = cd.get("alamat_apotek")
        telepon_apotek = cd.get("telepon_apotek")
        nama_penyelenggara = cd.get("nama_penyelenggara")
        no_sia = cd.get("no_sia")
        email = cd.get("email")

        if re.search('[\D]', str(no_sia)):
            self.add_error('no_sia', "No SIA contains Non-Digit character")

        if not bool(re.search('^\d{3} \d{3} \d{4}$', str(telepon_apotek))):
            self.add_error("telepon_apotek", "Wrong No Telp Apotek Format {XXX XXX XXXX}")

        return cd


class ProdukApotekForm(forms.Form):
    id_apotek = forms.CharField(max_length=10)
    id_produk = forms.CharField(max_length=10)
    harga_jual = forms.IntegerField()
    satuan_penjualan = forms.CharField(max_length=5)
    stok = forms.IntegerField()

    def clean(self):
        cd = self.cleaned_data
        id_apotek = cd.get("id_apotek")
        id_produk = cd.get("id_produk")
        harga_jual = cd.get("harga_jual")
        satuan_penjualan = cd.get("satuan_penjualan")
        stok = cd.get("stok")

        if re.search('[\D]', str(id_apotek)):
            self.add_error("id_apotek", "id_apotek contains Non-Digit character")

        if re.search('[\D]', str(id_produk)):
            self.add_error("id_produk", "id_produk contains Non-Digit character")

        if harga_jual < 0:
            self.add_error("harga_jual", "Harga Jual < 0")

        if stok < 0:
            self.add_error("harga_jual", "Stok < 0")

        return cd

apotek/views.py
from django.shortcuts import render, redirect
from django.db import connection, utils
from django.http import JsonResponse
from .forms import *
from login_register.decorators import *

# Create your views here.


def dictfetchall(cursor):
    columns = [col[0] for col in cursor.description]
    return [
        dict(zip(columns, row))
        for row in cursor.fetchall()
    ]


@login_required
def list_apotek(request):
    with connection.cursor() as cursor:
        cursor.execute("SELECT * FROM apotek ORDER BY id_apotek::numeric")
        rows = dictfetchall(cursor)
        return render(request, 'apotek/list_apotek.html', {'content': rows})


@login_required
def list_produk_apotek(request):
    # content_produk_apotek = DataApotek.data_produk_apotek.to_dict('records')
    # return render(request, 'apotek/list_produk_apotek.html', {"content":content_produk_apotek})
    with connection.cursor() as cursor:
        cursor.execute("SELECT * FROM produk_apotek ORDER BY id_produk::numeric , id_apotek::numeric ")
        rows = dictfetchall(cursor)
        return render(request, 'apotek/list_produk_apotek.html', {'content': rows})


@login_required
@admin_required
def delete_apotek(request, id):
    with connection.cursor() as cursor:
        cursor.execute("DELETE FROM apotek WHERE id_apotek = %s", [id])
        return redirect('apotek:list_apotek')


@login_required
@admin_required
def delete_produk_apotek(request, id_apotek, id_produk):
    with connection.cursor() as cursor:
        cursor.execute("DELETE FROM produk_apotek WHERE id_apotek = %s AND id_produk = %s", [id_apotek, id_produk])
        return redirect('apotek:list_produk_apotek')


@login_required
@admin_required
def update_apotek(request, id):
    with connection.cursor() as cursor:
        if request.method == "GET":
            cursor.execute("SELECT * FROM apotek WHERE id_apotek = %s", [id])
            row = dictfetchall(cursor)[0]
            print(row)
            return render(request, 'apotek/update_apotek.html', {"data": row})
        elif request.method == "POST":
            form = UpdateApotekForm(request.POST)
            print(request.POST)
            data = dict(map(lambda kv: (kv[0], kv[1][0]), dict(request.POST).items()))
            if form.is_valid():
                cd = form.cleaned_data
                id_apotek = cd.get("id_apotek")
                nama_apotek = cd.get("nama_apotek")
                alamat_apotek = cd.get("alamat_apotek")
                telepon_apotek = cd.get("telepon_apotek")
                nama_penyelenggara = cd.get("nama_penyelenggara")
                no_sia = cd.get("no_sia")
                email = cd.get("email")


                query = "UPDATE apotek SET nama_apotek = %s, "\
                        "alamat_apotek = %s, telepon_apotek = %s, nama_penyelenggara = %s, "\
                        "no_sia = %s, email = %s WHERE id_apotek = %s"

                try:
                    cursor.execute(query, [nama_apotek, alamat_apotek,telepon_apotek,
                                           nama_penyelenggara, no_sia, email, id_apotek])
                except utils.IntegrityError as e:
                    return render(request, 'apotek/update_apotek.html', {"data": data,
                                                                         "message" : str(e)})

                return redirect("apotek:list_apotek")

            return render(request, 'apotek/update_apotek.html', {"data": data, "form" : form})


@login_required
@admin_required
def update_produk_apotek(request, id_apotek, id_produk):
    with connection.cursor() as cursor:
        list_id_apotek = get_apotek_choices()
        list_id_produk = id_produk_choices_raw(id_apotek)
        list_id_produk.append(id_produk)
        list_id_produk.sort(key=lambda x: int(x))

        if request.method == "GET":
            list_id_apotek = get_apotek_choices()
            list_id_produk = id_produk_choices_raw(id_apotek)
            list_id_produk.append(id_produk)
            list_id_produk.sort(key= lambda x : int(x))
            cursor.execute("SELECT * FROM produk_apotek WHERE id_apotek = %s AND id_produk = %s"
                           , [id_apotek, id_produk])
            row = dictfetchall(cursor)[0]
            return render(request, 'apotek/update_produk_apotek.html',
                           {"data": row, "list_id_apotek": list_id_apotek,
                            "list_id_produk": list_id_produk})

        elif request.method == "POST":
            form = ProdukApotekForm(request.POST)
            data = dict(map(lambda kv: (kv[0], kv[1][0]), dict(request.POST).items()))
            if form.is_valid():
                cd = form.cleaned_data
                id_apotek_new = cd.get("id_apotek")
                id_produk_new = cd.get("id_produk")
                harga_jual = cd.get("harga_jual")
                satuan_penjualan = cd.get("satuan_penjualan")
                stok = cd.get("stok")

                query = "UPDATE produk_apotek SET id_apotek = %s, " \
                        "id_produk = %s, harga_jual = %s, satuan_penjualan = %s, " \
                        "stok = %s WHERE id_apotek = %s AND id_produk = %s"
                try:
                    cursor.execute(query, [id_apotek_new, id_produk_new, harga_jual,
                                           satuan_penjualan, stok, id_apotek, id_produk])

                except utils.IntegrityError as e:
                    return render(request, 'apotek/update_apotek.html', {"data": data,
                                                                         "message" : str(e)})
                return redirect("apotek:list_produk_apotek")

            return render(request, 'apotek/update_produk_apotek.html',
                          {"data": data, "list_id_apotek": list_id_apotek,
                           "list_id_produk": list_id_produk, "form" : form})


@login_required
@admin_required
def create_apotek(request):
    with connection.cursor() as cursor:
        if request.method == "GET":
            return render(request, "apotek/create_apotek.html")
        elif request.method == "POST":
            form = CreateApotekForm(request.POST)
            if form.is_valid():
                cursor.execute("SELECT id_apotek FROM apotek ORDER BY id_apotek::numeric DESC LIMIT 1")
                id_apotek = dictfetchall(cursor)[0]["id_apotek"]
                id_apotek = str(int(id_apotek) + 1)

                cd = form.cleaned_data
                nama_apotek = cd.get("nama_apotek")
                alamat_apotek = cd.get("alamat_apotek")
                telepon_apotek = cd.get("telepon_apotek")
                nama_penyelenggara = cd.get("nama_penyelenggara")
                no_sia = cd.get("no_sia")
                email = cd.get("email")

                query = "INSERT INTO apotek(id_apotek, email, no_sia, " \
                        "nama_penyelenggara, nama_apotek, alamat_apotek, telepon_apotek) " \
                        "VALUES(%s, %s, %s, %s, %s, %s, %s);"

                try:
                    cursor.execute(query, [id_apotek, email,
                                           no_sia, nama_penyelenggara, nama_apotek,
                                           alamat_apotek, telepon_apotek])
                except utils.IntegrityError as e:
                    return render(request, "apotek/create_apotek.html", {"message" : str(e)})

                return redirect("apotek:list_apotek")

            return render(request, "apotek/create_apotek.html", {"form" : form})


@login_required
@admin_required
def create_produk_apotek(request):
    with connection.cursor() as cursor:
        list_id_apotek = get_apotek_choices()

        if request.method == "GET":
            list_id_produk = id_produk_choices_raw(list_id_apotek[0])
            return render(request, "apotek/create_produk_apotek.html",
                          {"list_id_apotek": list_id_apotek,
                           "list_id_produk": list_id_produk})

        elif request.method == "POST":
            form = ProdukApotekForm(request.POST)
            data = dict(map(lambda kv: (kv[0], kv[1][0]), dict(request.POST).items()))
            list_id_produk = id_produk_choices_raw(data["id_apotek"])

            if form.is_valid():
                cd = form.cleaned_data
                id_apotek = cd.get("id_apotek")
                id_produk = cd.get("id_produk")
                harga_jual = cd.get("harga_jual")
                satuan_penjualan = cd.get("satuan_penjualan")
                stok = cd.get("stok")

                query = "INSERT INTO produk_apotek(harga_jual, stok, satuan_penjualan, " \
                        "id_produk, id_apotek) " \
                        "VALUES(%s, %s, %s, %s, %s);"
                try:
                    cursor.execute(query, [harga_jual, stok,satuan_penjualan,
                                           id_produk, id_apotek])

                except utils.IntegrityError as e:
                    return render(request, 'apotek/create_produk_apotek.html',
                                  {"data": data, "list_id_apotek": list_id_apotek,
                                   "list_id_produk": list_id_produk,
                                   "message": str(e)})

                return redirect("apotek:list_produk_apotek")

            return render(request, "apotek/create_produk_apotek.html",
                          {"data": data, 'form': form,
                           "list_id_apotek": list_id_apotek,
                           "list_id_produk": list_id_produk})


def get_apotek_choices():
    with connection.cursor() as cursor:
        cursor.execute("SELECT id_apotek FROM apotek ORDER BY id_apotek::numeric ")
        apotek_cursor = dictfetchall(cursor)

        apotek = []

        for row in apotek_cursor:
            apotek.append(row['id_apotek'])

        return apotek


def id_produk_choices_raw(id):
    with connection.cursor() as cursor:

apotek/templates/apotek/base_apotek.html
{% extends 'base_with_login.html' %}
{% load static  %}
{% block title  %}
    {% block title_apotek %}
    {% endblock %}
{% endblock %}

{% block content %}
    {% block title_below %}
    {% endblock %}
    <div class="mb-2 mt-2">
    <a href="{% url 'apotek:list_apotek' %}">
          <button type="button" class="btn btn-sm btn-primary">Daftar Apotek</button>
    </a>
    {% if request.session.role == "ADMIN_APOTEK" %}
    <a href="{% url 'apotek:create_apotek' %}">
          <button type="button" class="btn btn-sm btn-primary">Create Apotek</button>
    </a>
    {% endif %}
    <a href="{% url 'apotek:list_produk_apotek' %}">
          <button type="button" class="btn btn-sm btn-primary">Daftar Produk Apotek</button>
    </a>
    {% if request.session.role == "ADMIN_APOTEK" %}
    <a href="{% url 'apotek:create_produk_apotek' %}">
          <button type="button" class="btn btn-sm btn-primary">Create Produk Apotek</button>
    </a>
    {% endif %}
    </div>
    {% block content_apotek %}
    {% endblock %}
{% endblock %}

apotek/templates/apotek/create_apotek.html
{% extends 'apotek/base_apotek.html' %}

{% block title_apotek %}
    <title>Create Apotek</title>
{% endblock %}

{% block title_below %}
    <h1 class="text-center">Create Apotek</h1>
    {% endblock %}
{% block content_apotek %}
    {% if form or message %}
    <div class="alert alert-danger" role="alert">
        <ul>
        {% if form %}
            {% for field, errors in form.errors.items %}
                {% for error in errors %}
                    <li>{{ error }}</li>
                {% endfor %}
            {% endfor %}
        {% endif %}
        {% if message %}
            <li>{{ message }}</li>
        {% endif %}
        </ul>
    </div>
    {% endif %}

    <div>
    <form method="post">
        {% csrf_token %}
      <div class="form-group">
        <label for="nama_apotek">Nama Apotek</label>
        <input type="text" name="nama_apotek"  class="form-control" id="nama_apotek" placeholder="Nama Apotek" required>
      </div>
       <div class="form-group">
        <label for="alamat_apotek">Alamat Apotek</label>
        <input type="text" name="alamat_apotek" class="form-control" id="alamat_apotek" placeholder="Alamat Apotek" required>
      </div>
      <div class="form-group">
        <label for="telepon_apotek">No telp Apotek</label>
        <input type="text" name="telepon_apotek" class="form-control" id="telepon_apotek" placeholder="No Telp Apotek" required>
      </div>
       <div class="form-group">
        <label for="nama_penyelenggara">Nama Penyelenggara</label>
        <input type="text" name="nama_penyelenggara" class="form-control" id="nama_penyelenggara" placeholder="Nama Penyelenggara" required>
      </div>
       <div class="form-group">
        <label for="no_sia">No SIA Penyelenggara</label>
        <input type="text" name="no_sia" class="form-control" id="no_sia" placeholder="No SIA Penyelenggara" required>
      </div>
       <div class="form-group">
        <label for="email">Email Penyelenggara</label>
        <input type="email" name="email" class="form-control" id="email" placeholder="Email" required>
      </div>
        <div class="d-flex justify-content-center">
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </form>
    </div>
{% endblock %}

apotek/templates/apotek/create_produk_apotek.html
{% extends 'apotek/base_apotek.html' %}
{% load static %}

{% block cssJs %}
<script src = "{% static 'create_produk_apotek.js' %}"></script>
{% endblock %}

{% block title_apotek %}
    <title>Create Produk Apotek</title>
{% endblock %}

{% block title_below %}
    <h1 class="text-center">Create Produk Apotek</h1>
    {% endblock %}
{% block content_apotek %}
    {% if form or message %}
    <div class="alert alert-danger" role="alert">
        <ul>
        {% if form %}
            {% for field, errors in form.errors.items %}
                {% for error in errors %}
                    <li>{{ error }}</li>
                {% endfor %}
            {% endfor %}
        {% endif %}
        {% if message %}
            <li>{{ message }}</li>
        {% endif %}
        </ul>
    </div>
    {% endif %}
    <div>
    <form method="post">
    {% csrf_token %}
      <div class="form-group">
        <label for="id_apotek">ID Apotek</label>
        <select name="id_apotek" class="form-control" id="id_apotek">
          {% for id_apotek in list_id_apotek %}
              {% if id_apotek == data.id_apotek %}
                <option value="{{ id_apotek }}" selected>{{ id_apotek }}</option>
              {% else %}
                  <option value="{{ id_apotek }}">{{ id_apotek }}</option>
            {% endif %}
        {% endfor %}
        </select>
      </div>
      <div class="form-group">
        <label for="id_produk">ID Produk</label>
        <select name="id_produk" class="form-control" id="id_produk">
          {% for id_produk in list_id_produk %}
              {% if id_produk == data.id_produk %}
                <option value="{{ id_produk }}" selected>{{ id_produk }}</option>
              {% else %}
                  <option value="{{ id_produk }}">{{ id_produk }}</option>
            {% endif %}
        {% endfor %}
        </select>
      </div>
      <div class="form-group">
        <label for="harga_jual">Harga Jual</label>
        <input type="number" name="harga_jual"  class="form-control" id="harga_jual" placeholder="Masukkan Harga" required
               value="{{ data.harga_jual }}" min="0">
      </div>
       <div class="form-group">
        <label for="satuan_penjualan">Satuan Penjualan</label>
        <input type="text" name="satuan_penjualan" class="form-control" id="satuan_penjualan" placeholder="Masukkan Jenis Satuan" required
               value="{{ data.satuan_penjualan }}" maxlength="5">
      </div>
      <div class="form-group">
        <label for="stok">Stok</label>
        <input type="number" name="stok" class="form-control" id="stok" placeholder="Masukkan Jumlah stok" required
               value="{{ data.stok }}" min="0">
      </div>
        <div class="d-flex justify-content-center">
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </form>
    </div>
{% endblock %}

apotek/templates/apotek/list_apotek.html
{% extends 'apotek/base_apotek.html' %}

{% block title_apotek %}
    <title>Apotek</title>
{% endblock %}

    {% block title_below %}
    <h1 class="text-center">Daftar Apotek</h1>
    {% endblock %}
    {% block content_apotek %}
    <table class="table">
  <thead>
    <tr>
      <th scope="col">ID Apotek</th>
      <th scope="col">Nama Apotek</th>
      <th scope="col">Alamat Apotek</th>
      <th scope="col">No Telp Apotek</th>
      <th scope="col">Nama Penyelenggara</th>
      <th scope="col">No SIA Penyelenggara</th>
      <th scope="col">Email Penyelenggara</th>
      {% if request.session.role == "ADMIN_APOTEK" %}
      <th scope="col">Action</th>
      {% endif %}
    </tr>
  </thead>
  <tbody>
  {% for data in content  %}
    <tr>
      <td>{{ data.id_apotek }}</td>
      <td>{{ data.nama_apotek }}</td>
      <td>{{ data.alamat_apotek }}</td>
      <td>{{ data.telepon_apotek }}</td>
      <td>{{ data.nama_penyelenggara }}</td>
      <td>{{ data.no_sia }}</td>
      <td>{{ data.email }}</td>
      {% if request.session.role == "ADMIN_APOTEK" %}
      <td>
          <a href="{% url 'apotek:delete_apotek' id=data.id_apotek %}">
          <button type="delete" class="btn btn-sm btn-primary"> Delete</button>
          </a>
          <a href="{% url 'apotek:to_update_apotek' id=data.id_apotek %}">
          <button type="button" class="btn btn-sm btn-primary">Update</button>
          </a>
      </td>
      {% endif %}
    </tr>
  </tbody>
  {% endfor %}
</table>
{% endblock %}

apotek/templates/apotek/list_produk_apotek.html
{% extends 'apotek/base_apotek.html' %}

{% block title_apotek %}
    <title>Produk Apotek</title>
{% endblock %}

{% block title_below %}
    <h1 class="text-center">Produk Apotek</h1>
    {% endblock %}
{% block content_apotek %}
 <table class="table">
  <thead>
    <tr>
      <th scope="col">ID Produk</th>
      <th scope="col">ID Apotek</th>
      <th scope="col">Harga Jual</th>
      <th scope="col">Satuan Penjualan</th>
      <th scope="col">Stok</th>
      {% if request.session.role == "ADMIN_APOTEK" %}
      <th scope="col">Action</th>
      {% endif %}
    </tr>
  </thead>
  <tbody>
   {% for data in content  %}
    <tr>
      <td>{{ data.id_produk }}</td>
      <td>{{ data.id_apotek }}</td>
      <td>{{ data.harga_jual }}</td>
      <td>{{ data.satuan_penjualan }}</td>
      <td>{{ data.stok}}</td>
      {% if request.session.role == "ADMIN_APOTEK" %}
      <td>
          <a href="{% url 'apotek:delete_produk_apotek' id_apotek=data.id_apotek id_produk=data.id_produk %}">
              <button type="button" class="btn btn-sm btn-primary">Delete</button>
          </a>
          <a href="{% url 'apotek:to_update_produk_apotek' id_apotek=data.id_apotek id_produk=data.id_produk %}">
              <button type="button" class="btn btn-sm btn-primary">Update</button>
          </a>
      </td>
      {% endif %}
    </tr>
  {% endfor %}
 </tbody>
</table>
{% endblock %}

apotek/templates/apotek/update_apotek.html
{% extends 'apotek/base_apotek.html' %}

{% block title_apotek %}
    <title>Update Apotek</title>
{% endblock %}

{% block title_below %}
    <h1 class="text-center">Update Apotek</h1>
    {% endblock %}
{% block content_apotek %}
    {% if form or message %}
    <div class="alert alert-danger" role="alert">
        <ul>
        {% if form %}
            {% for field, errors in form.errors.items %}
                {% for error in errors %}
                    <li>{{ error }}</li>
                {% endfor %}
            {% endfor %}
        {% endif %}
        {% if message %}
            <li>{{ message }}</li>
        {% endif %}
        </ul>
    </div>
    {% endif %}
    <div>
    <form method="post">
        {% csrf_token %}
      <div class="form-group">
        <label for="id_apotek">ID Apotek</label>
        <input type="text" readonly class="form-control" id="id_apotek" name="id_apotek" placeholder="Id" required
               value="{{ data.id_apotek }}" maxlength="10">
      </div>
      <div class="form-group">
        <label for="nama_apotek">Nama Apotek</label>
        <input type="text" name="nama_apotek" class="form-control" id="nama_apotek" placeholder="Nama Apotek" required
               value="{{ data.nama_apotek }}" maxlength="50">
      </div>
       <div class="form-group">
        <label for="alamat_apotek">Alamat Apotek</label>
        <input type="text" name="alamat_apotek" class="form-control" id="alamat_apotek" placeholder="Alamat Apotek" required
               value="{{ data.alamat_apotek }}">
      </div>
      <div class="form-group">
        <label for="telepon_apotek">No telp Apotek</label>
        <input type="text" name="telepon_apotek" class="form-control" id="telepon_apotek" placeholder="No Telp Apotek" required
               value="{{ data.telepon_apotek }}" maxlength="20">
      </div>
       <div class="form-group">
        <label for="nama_penyelenggara">Nama Penyelenggara</label>
        <input type="text" name="nama_penyelenggara" class="form-control" id="nama_penyelenggara" placeholder="Nama Penyelenggara" required
               value="{{ data.nama_penyelenggara }}" maxlength="50">
      </div>
       <div class="form-group">
        <label for="no_sia">No SIA Penyelenggara</label>
        <input type="text" name="no_sia" class="form-control" id="no_sia" placeholder="No SIA Penyelenggara" required
               value="{{ data.no_sia }}" maxlength="20">
      </div>
       <div class="form-group">
        <label for="email">Email Penyelenggara</label>
        <input type="email" name="email" class="form-control" id="email" placeholder="Email" required
               value="{{ data.email }}" maxlength = "50">
      </div>
        <div class="d-flex justify-content-center">
            <button type="submit" class="btn btn-primary">Update</button>
        </div>
    </form>
    </div>
{% endblock %}

apotek/templates/apotek/update_produk_apotek.html
{% extends 'apotek/base_apotek.html' %}
{% load static  %}
{% block cssJs %}
<script src = "{% static 'update_produk_apotek.js' %}"></script>
{% endblock %}
{% block title %}
    <title>Update Produk Apotek</title>
{% endblock %}

{% block title_below %}
    <h1 class="text-center">Update Produk Apotek</h1>
{% endblock %}
{% block content_apotek %}
    {% if form or message %}
    <div class="alert alert-danger" role="alert">
        <ul>
        {% if form %}
            {% for field, errors in form.errors.items %}
                {% for error in errors %}
                    <li>{{ error }}</li>
                {% endfor %}
            {% endfor %}
        {% endif %}
        {% if message %}
            <li>{{ message }}</li>
        {% endif %}
        </ul>
    </div>
    {% endif %}
    <div>
    <form method="POST">
    {% csrf_token %}
      <div class="form-group">
        <label for="id_apotek">ID Apotek</label>
        <select name="id_apotek" class="form-control" id="id_apotek">
          {% for id_apotek in list_id_apotek %}
              {% if id_apotek == data.id_apotek %}
                <option value="{{ id_apotek }}" selected>{{ id_apotek }}</option>
              {% else %}
                  <option value="{{ id_apotek }}">{{ id_apotek }}</option>
            {% endif %}
        {% endfor %}
        </select>
      </div>
      <div class="form-group">
        <label for="id_produk">ID Produk</label>
        <select name="id_produk" class="form-control" id="id_produk">
            {% for id_produk in list_id_produk %}
                {% if id_produk == data.id_produk %}
                    <option value="{{ id_produk }}" selected>{{ id_produk }}</option>
                  {% else %}
                      <option value="{{ id_produk }}">{{ id_produk }}</option>
                {% endif %}
            {% endfor %}
        </select>
      </div>
      <div class="form-group">
        <label for="harga_jual">Harga Jual</label>
        <input type="number" name="harga_jual"  class="form-control" id="harga_jual" placeholder="Masukkan Harga" required
               value="{{ data.harga_jual }}">
      </div>
       <div class="form-group">
        <label for="satuan_penjualan">Satuan Penjualan</label>
        <input type="text" name="satuan_penjualan" class="form-control" id="satuan_penjualan" placeholder="Masukkan Jenis Satuan" required
               value="{{ data.satuan_penjualan }}" maxlength="5">
      </div>
      <div class="form-group">
        <label for="stok">Stok</label>
        <input type="number" name="stok" class="form-control" id="stok" placeholder="Masukkan Jumlah stok" required
               value="{{ data.stok }}">
      </div>
        <div class="d-flex justify-content-center">
            <button type="submit" class="btn btn-primary">Update</button>
        </div>
    </form>
    </div>
{% endblock %}