apotek/urls.py
from django.contrib import admin
from django.urls import path
from apotek import views

app_name = 'apotek'
urlpatterns = [
    path('', views.list_apotek, name ='list_apotek'),
    path('produk/', views.list_produk_apotek, name ='list_produk_apotek'),
    path('delete/<id>', views.delete_apotek, name ='delete_apotek'),
    path('produk/delete/<id_apotek>/<id_produk>', views.delete_produk_apotek, name ='delete_produk_apotek'),
    path('update/<id>', views.update_apotek, name ='to_update_apotek'),
    path('produk/update/<id_apotek>/<id_produk>', views.update_produk_apotek,
         name ='to_update_produk_apotek'),
    path('create/', views.create_apotek, name ='create_apotek'),
    path('produk/create/', views.create_produk_apotek, name ='create_produk_apotek'),
    path('produk/avlble/<id>', views.id_produk_choices, name = 'id_produk_choice')
]

balai_pengobatan/urls.py
from django.urls import path
from . import views


app_name = 'balai_pengobatan'

urlpatterns = [
    path('', views.balai, name="index"),
    path('create_balai', views.create_balai, name="create_balai"),
    path('delete_balai/<id>', views.delete_balai, name ='delete_balai'),
    path('update_balai/<id>', views.update_balai, name="update_balai"),
    path('obat', views.obat, name="obat"),
    path('obat/create_obat', views.create_obat, name="create_obat"),
    path('obat/update_obat/<id>', views.update_obat, name="update_obat"),
    path('obat/delete_obat/<id>', views.delete_obat, name="delete_obat")
]

list_produk_pengantaran/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'list_produk_pengantaran'

urlpatterns = [
	path('list_produk_dibeli/',views.list_produk_dibeli,name='list_produk_dibeli'),
    path('create_list_produk_dibeli/',views.create_list_produk_dibeli,name='create_list_produk_dibeli'),
    path('pengantaran_farmasi/',views.pengantaran_farmasi,name='pengantaran_farmasi'),
    path('create_pengantaran_farmasi/',views.create_pengantaran_farmasi,name='create_pengantaran_farmasi'),
    path('delete/<id>', views.delete_pengantaran_farmasi, name ='delete_pengantaran_farmasi'),
    path('produk/delete/<id_apotek>/<id_produk>/<id_transaksi_pembelian>', views.delete_list_produk_dibeli, name ='delete_list_produk_dibeli'),
    path('update_pengantaran_farmasi/<id>', views.update_pengantaran_farmasi, name ='update_pengantaran_farmasi'),
    path('update_list_produk_dibeli/<id_apotek>/<id_produk>/<id_transaksi_pembelian>', views.update_list_produk_dibeli,
         name ='update_list_produk_dibeli'),
    path('apotek/avlble/<id>', views.id_apotek_choices, name = 'id_apotek_choice')
]

login_register/urls.py
from django.urls import path
from . import views

app_name = 'login_register'

urlpatterns = [
    path('', views.home, name='landingpage'),
    path('login/', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('homepage/', views.homepage, name='homepage'),
    path('register/kurir/', views.kurir, name='kurir'),
    path('register/konsumen/', views.konsumen, name='konsumen'),
    path('register/admin-apotek/', views.admin_apotek, name='admin_apotek'),
    path('register/cs/', views.cs, name='cs'),
    path('logout/', views.logout, name="logout")
]

tk_basdat_43/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('login_register.urls')),
    path('transaksi_pembelian/', include('transaksi_pembelian.urls')),
    path('list_produk_pengantaran/',include('list_produk_pengantaran.urls', namespace = 'list_produk_pengantaran')),
    path('balai_pengobatan/', include('balai_pengobatan.urls')),
    path('apotek/', include('apotek.urls')),
]

transaksi_pembelian/urls.py
from django.urls import path
from . import views

app_name = 'transaksi_pembelian'

urlpatterns = [
    path('daftar_transaksi_pembelian/', views.daftar, name='daftar'),
    path('update_transaksi_pembelian/<id_transaksi_pembelian>/<waktu_pembelian>/<total_pembayaran>', views.update, name='update'),
    path('create_transaksi_pembelian/', views.create, name='create'),
    path('profil_pengguna/', views.profile, name='profil'),
    path('delete_transaksi_pembelian/<id_transaksi_pembelian>', views.delete, name='delete'),
]

transaksi_pembelian/models.py
from django.db import models

# Create your models here.

transaksi_pembelian/forms.py
from django import forms

idkonsumen = [
    ('1',"1"),
    ('2',"2"),
    ('3',"3"),
    ('4',"4"),
    ('5',"5"),
]

class createtr(forms.Form):
    id_konsumen = forms.CharField(label='id_konsumen', max_length=10, required=True)
    

class updatetr(forms.Form):
    id_konsumen = forms.CharField(label='id_konsumen', max_length=10, required=True)

    

transaksi_pembelian/views.py
from django.shortcuts import redirect, render

import os
from django.db import connection, utils
from collections import namedtuple
from .forms import createtr, updatetr
from tk_basdat_43.settings import STATIC_DIR
from .data import DataTransaksi
from login_register.decorators import *

# Create your views here.
def namedtuplefetchall(cursor):
    "Return all rows from a cursor as a namedtuple"
    desc = cursor.description
    nt_result = namedtuple('Result', [col[0] for col in desc])
    return [nt_result(*row) for row in cursor.fetchall()]
    
@login_required
def daftar(request):
    dataset = []
    cursor = connection.cursor()
    email = request.session["email"]
    role = request.session["role"]

    if role == "KONSUMEN":
        sql = "SELECT * FROM FARMAKAMI.konsumen WHERE email ='"+ email +"';"
        cursor.execute(sql)
        dataset = namedtuplefetchall(cursor)
        id_konsumen = dataset[0].id_konsumen
        sql2 = "SELECT * FROM FARMAKAMI.TRANSAKSI_PEMBELIAN WHERE id_konsumen ='"+id_konsumen+"';"
        cursor.execute(sql2)
        dataset = namedtuplefetchall(cursor)
        return render(request, 'daftar_transaksi_pembelian.html', {"table":dataset})

    else:
        sql_daftar = "SELECT * FROM farmakami.TRANSAKSI_PEMBELIAN"
        cursor.execute(sql_daftar)
        dataset = namedtuplefetchall(cursor)
        return render(request, 'daftar_transaksi_pembelian.html', {"table":dataset})

@login_required
@admin_required
def update(request, id_transaksi_pembelian, waktu_pembelian, total_pembayaran):
    if request.method =='POST':
        update_form = request.POST["id_konsumen_select"]

        cursor = connection.cursor()

        if update_form != "none":
            sql = "update farmakami.transaksi_pembelian set id_konsumen = '" + update_form + "' where id_transaksi_pembelian = '" + id_transaksi_pembelian + "';"
            cursor.execute(sql)
            sql2 = "update farmakami.transaksi_pembelian set waktu_pembelian = NOW() where id_transaksi_pembelian = '" + id_transaksi_pembelian + "';"
            cursor.execute(sql2)

        return redirect('/transaksi_pembelian/daftar_transaksi_pembelian/')

    form = updatetr()
    cursor = connection.cursor()
    sql_idkonsumen = "select distinct id_konsumen from farmakami.konsumen order by id_konsumen ASC"
    cursor.execute(sql_idkonsumen)
    idkonsumen = namedtuplefetchall(cursor)
    args = {'form': form, 'id_transaksi_pembelian':id_transaksi_pembelian, 'waktu_pembelian':waktu_pembelian, 'total_pembayaran':total_pembayaran, 'idkonsumen':idkonsumen}
    return render(request, 'update_transaksi_pembelian.html', args)

@login_required
@admin_required
def create(request):
    context = {}
    if request.method =='POST':
        form = createtr(request.POST)
        context['form'] = form
        id_konsumen = request.POST["id_konsumen_select"]
        

        cursor = connection.cursor()

        temp = "select count(*) from farmakami.transaksi_pembelian"
        cursor.execute(temp)
        temp2 = cursor.fetchone()[0]

        temp3 = str(temp2)
        sql = "select count(*) from farmakami.transaksi_pembelian where id_transaksi_pembelian = '" + temp3 + "';"
        cursor.execute(sql)
        final = cursor.fetchone()[0]

        while(final != 0):
            temp2 = temp2 + 1
            temp3 = str(temp2)
            sql = "select count(*) from farmakami.transaksi_pembelian where id_transaksi_pembelian = '" + temp3 + "';"
            cursor.execute(sql)
            final = cursor.fetchone()[0]

        idtransaksi = "" + str(temp2)
        sql_create = "insert into farmakami.transaksi_pembelian VALUES (%s, NOW(), %s, %s);"
        cursor.execute(sql_create,(idtransaksi, 0, id_konsumen))
        return redirect('/transaksi_pembelian/daftar_transaksi_pembelian/')

    else:
        form = createtr()
    
    cursor = connection.cursor()
    sql_idkonsumen = "select distinct id_konsumen from farmakami.konsumen order by id_konsumen ASC"
    cursor.execute(sql_idkonsumen)
    idkonsumen = namedtuplefetchall(cursor)
    args = {'form': form, 'idkonsumen': idkonsumen}

    return render(request, 'create_transaksi_pembelian.html', args)

@login_required
@admin_required
def delete(request, id_transaksi_pembelian):
    cursor = connection.cursor()
    sql_delete = "delete from farmakami.TRANSAKSI_PEMBELIAN where id_transaksi_pembelian = '" + id_transaksi_pembelian + "'"
    cursor.execute(sql_delete)
    return redirect('/transaksi_pembelian/daftar_transaksi_pembelian/')

@login_required
def profile(request):
    email = request.session["email"]
    role = request.session["role"]
    cursor = connection.cursor()

    sql_pengguna = "SELECT * FROM FARMAKAMI.PENGGUNA WHERE email='"+email+"';"
    cursor.execute(sql_pengguna)
    data = namedtuplefetchall(cursor)
    pengguna = data[0]

    if role == "ADMIN_APOTEK":
        sql_admin = "SELECT * FROM FARMAKAMI.ADMIN_APOTEK WHERE email='"+email+"';"
        cursor.execute(sql_admin)
        data  = namedtuplefetchall(cursor)
        admin = data[0]
        return render(request, 'profil_pengguna.html', {"pengguna":pengguna, "admin":admin})

    elif role == "KONSUMEN":
        sql_konsumen = "SELECT * FROM FARMAKAMI.KONSUMEN WHERE email='"+email+"';"
        cursor.execute(sql_konsumen)
        data= namedtuplefetchall(cursor)
        konsumen = data[0]

        id_konsumen = konsumen.id_konsumen
        sql_alamat = "SELECT * FROM FARMAKAMI.ALAMAT_KONSUMEN WHERE id_konsumen='"+id_konsumen+"';"
        cursor.execute(sql_alamat)
        data = namedtuplefetchall(cursor)
        alamat = data
        return render(request, 'profil_pengguna.html', {"pengguna":pengguna, "konsumen":konsumen, "alamat":alamat})

    elif role == "CS":
        sql_cs = "SELECT * FROM FARMAKAMI.CS WHERE email='"+email+"';"
        cursor.execute(sql_cs)
        data  = namedtuplefetchall(cursor)
        cs = data[0]
        return render(request, 'profil_pengguna.html', {"pengguna":pengguna, "cs":cs})

    elif role == "KURIR":
        sql_kurir = "SELECT * FROM FARMAKAMI.KURIR WHERE email='"+email+"';"
        cursor.execute(sql_kurir)
        data  = namedtuplefetchall(cursor)
        kurir = data[0]
        return render(request, 'profil_pengguna.html', {"pengguna":pengguna, "kurir":kurir})

transaksi_pembelian/templates/basetr.html
{% load static  %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.js" integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    {% block cssJs %}
    {% endblock %}
    {% block title %}
    {% endblock %}
</head>
<body>
<nav class="navbar sticky-top navbar-expand-lg navbar-dark bg-dark mb-2">
  <a class="navbar-brand" href="{% url 'login_register:homepage' %}">Home</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <ul class="navbar-nav mr-auto">
       <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Profil
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'transaksi_pembelian:profil' %}">Profil Pengguna</a>
        </div>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Balai Pengobatan & Apotek
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'apotek:list_apotek' %}">Daftar Apotek</a>
          {% if request.session.role == "ADMIN_APOTEK" %}
          <a class="dropdown-item" href="{% url 'apotek:create_apotek' %}">Create Apotek</a>
          {% endif %}
          <a class="dropdown-item" href="{% url 'balai_pengobatan:index' %}">Daftar Balai Pengobatan</a>
          {% if request.session.role == "ADMIN_APOTEK" %}
          <a class="dropdown-item" href="{% url 'balai_pengobatan:create_balai' %}">Create Balai Pengobatan</a>
          {% endif %}
        </div>
      </li>
        <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Transaksi
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'transaksi_pembelian:daftar' %}">Daftar Transaksi Pembelian</a>
          {% if request.session.role == "ADMIN_APOTEK" %}
          <a class="dropdown-item" href="{% url 'transaksi_pembelian:create' %}">Create Transaksi Pembelian</a>
          {% endif %}
        </div>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Produk Apotek
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          {% if request.session.role == "ADMIN_APOTEK" %}
          <a class="dropdown-item" href="{% url 'apotek:create_produk_apotek' %}">Create Produk Apotek</a>
          {% endif %}
          <a class="dropdown-item" href="{% url 'apotek:list_produk_apotek' %}">Daftar Produk Apotek</a>
        </div>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Produk Dibeli
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          {% if request.session.role == "ADMIN_APOTEK" %}
          <a class="dropdown-item" href="{% url 'list_produk_pengantaran:create_list_produk_dibeli' %}">Create Produk Dibeli</a>
          {% endif %}
          <a class="dropdown-item" href="{% url 'list_produk_pengantaran:list_produk_dibeli' %}">Daftar Produk Dibeli</a>
        </div>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Pengantaran
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          {% if request.session.role == "ADMIN_APOTEK" %}
          <a class="dropdown-item" href="{% url 'list_produk_pengantaran:create_pengantaran_farmasi' %}">Create Pengantaran Farmasi</a>
          {% endif %}
          <a class="dropdown-item" href="{% url 'list_produk_pengantaran:pengantaran_farmasi' %}">Daftar Pengantaran Farmasi</a>
        </div>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Produk Medis
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          {% if request.session.role == "ADMIN_APOTEK" %}
          <a class="dropdown-item" href="{% url 'list_produk_pengantaran:create_pengantaran_farmasi' %}">Create Pengantaran Farmasi</a>
          {% endif %}
          <a class="dropdown-item" href="{% url 'list_produk_pengantaran:pengantaran_farmasi' %}">Daftar Pengantaran Farmasi</a>
        </div>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Obat
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          {% if request.session.role == "ADMIN_APOTEK" %}
          <a class="dropdown-item" href="{% url 'balai_pengobatan:create_obat' %}">Create Obat</a>
          {% endif %}
          <a class="dropdown-item" href="{% url 'balai_pengobatan:obat' %}">Daftar Obat</a>
        </div>
      </li>
    </ul>
      <form class="form-inline my-2 my-lg-0 mr-4">
        <a href="{% url 'login_register:logout' %}">
          <button class="btn btn-danger my-2 my-sm-0" type="button">Logout</button>
        </a>
      </form>
    </div>
  </div>
</nav>
{% block content %}
{% endblock %}
</body>
</html>

transaksi_pembelian/templates/create_transaksi_pembelian.html
{% extends 'basetr.html' %}
{% load static %}
{% block cssJs %}
    <link rel="stylesheet" href="{% static 'create.css' %}">
{% endblock %}
{% block title %}
    <title>Create Transaksi Pembelian</title>
{% endblock %}

{% block content %}
    <div>
        <h1>Create Transaksi Pembelian</h1>
        <form method="post">
            {% csrf_token %}
            <table>
                
                <tr>
                    <td>ID Konsumen</td>
                    <td>
                        <select name="id_konsumen_select" id="id_konsumen_select">
                            <option value="none">none</option>
                            {% for id in idkonsumen %}
                                <option value="{{id.id_konsumen}}">{{id.id_konsumen}}</option>
                            {%  endfor %}
                        </select>
                    </td>
                </tr>
                <tr>
                    <td>
                        <button type="submit" class="btn btn-sm btn-primary">SUBMIT</button>
                    </td>
                </tr>
            </table>
        </form>
    </div>
{% endblock %}

transaksi_pembelian/templates/daftar_transaksi_pembelian.html
{% extends 'basetr.html' %}
{% load static %}
{% block cssJs %}
    <link rel="stylesheet" href="{% static 'daftar_transaksi_pembeli.css' %}">
{% endblock %}
{% block title %}
    <title>Daftar Transaksi Pembelian</title>
{% endblock %}
{% block content %}
    <div>
        <table>
            <h1>Daftar Transaksi Pembelian</h1>
            <tr>
                <th>ID Transaksi</th>
                <th>Waktu Pembelian</th>
                <th>Total Pembayaran</th>
                {% if request.session.role != "KONSUMEN" %}
                <th>ID Konsumen</th>
                {% endif %}
                {% if request.session.role == "ADMIN_APOTEK" %}
                <th>Action</th>
                {% endif %}
            </tr>
            
            {% for item in table %}
            <tr>
                <td>{{ item.id_transaksi_pembelian }}</td>
                <td>{{ item.waktu_pembelian }}</td>
                <td>{{ item.total_pembayaran }}</td>
                {% if request.session.role != "KONSUMEN" %}
                <td>{{ item.id_konsumen }}</td>
                {% endif %}
                {% if request.session.role == "ADMIN_APOTEK" %}
                <td>
                    <a href="{% url 'transaksi_pembelian:update' item.id_transaksi_pembelian item.waktu_pembelian item.total_pembayaran %}"><button type="button" class="btn btn-sm btn-primary">Update</button></a>
                    <a href="{% url 'transaksi_pembelian:delete' item.id_transaksi_pembelian %}"><button type="button" class="btn btn-sm btn-primary">Delete</button></a> 
                </td>
                {% endif %}
            </tr>
            {% endfor %}
            
        </table>
    </div>
{% endblock %}    

transaksi_pembelian/templates/profil_pengguna.html
{% extends 'basetr.html' %}
{% load static %}
{% block cssJs %}
    <link rel="stylesheet" href="{% static 'profil.css' %}">
{% endblock %}
{% block title %}
    <title>Profil Pengguna</title>
{% endblock %}
{% block content %}
    <div>
        <h1>Profil Pengguna</h1>
        <table>
            <tr>
                <th>Email</th>
                <th>Password</th>
                <th>Nama Lengkap</th>
                <th>No Telepon</th>

                {% if request.session.role == "KONSUMEN" %}
                <th>Jenis Kelamin</th>
                <th>Tanggal Lahir</th>
                <th>Alamat</th>
                {% endif %}

                {% if request.session.role == "KURIR" %}
                <th>Nama Perusahaan</th>
                {% endif %}

                {% if request.session.role == "CS" %}
                <th>No KTP</th>
                <th>No SIA</th>
                {% endif %}
            </tr>

            
            <tr>
                <td>{{ pengguna.email }}</td>
                <td>{{ pengguna.password }}</td>
                <td>{{ pengguna.nama_lengkap }}</td>
                <td>{{ pengguna.telepon }}</td>

                {% if request.session.role == "KONSUMEN" %}
                <td>{{ konsumen.jenis_kelamin }}</td>
                <td>{{ konsumen.tanggal_lahir }}</td>
                <td>
                    <p>
                        {% for alamat_pengguna in alamat %}
                        <br>
                       {{ alamat_pengguna.alamat }}
                       <br>
                       {% endfor %}
                    </p>
                </td>
                {% endif %}

                {% if request.session.role == "KURIR" %}
                <td>{{ kurir.nama_perusahaan }}</td>
                {% endif %}

                {% if request.session.role == "CS" %}
                <td>{{ cs.no_ktp }}</td>
                <td>{{ cs.no_sia }}</td>
                {% endif %}
            </tr>
        
        </table>
    </div>
{% endblock %}

transaksi_pembelian/templates/update_transaksi_pembelian.html
{% extends 'basetr.html' %}
{% load static %}
{% block cssJs %}
    <link rel="stylesheet" href="{% static 'update.css' %}">
{% endblock %}
{% block title %}
    <title>Update Transaksi Pembelian</title>
{% endblock %}
{% block content %}
    <div>
        <h1>Update Transaksi Pembelian</h1>
        <form method="POST">
            {% csrf_token %}
            
            <table>
                <tr>
                    <td>ID Transaksi</td>
                    <td>
                        <input type="text" name="ID Transaksi" id="id_transaksi_pembelian" value={{ id_transaksi_pembelian }} disabled>
                    </td>
                </tr>
                <tr>
                    <td>Waktu Pembelian</td>
                    <td>
                        <input type="text" name="Waktu Pembelian" id="waktu_pembelian" value={{ waktu_pembelian }} disabled>
                    </td>
                </tr>
                <tr>
                    <td>Total Pembayaran</td>
                    <td>
                        <input type="text" name="Total Pembayaran" id="total_pembayaran"  value={{ total_pembayaran }} disabled>
                    </td>
                </tr>
                <tr>
                    <td>ID Konsumen</td>
                    <td>
                        <select name="id_konsumen_select" id="id_konsumen_select">
                            <option value="none">none</option>
                            {% for id in idkonsumen %}
                                <option value="{{id.id_konsumen}}">{{id.id_konsumen}}</option>
                            {%  endfor %}
                        </select>
                        
                    </td>
                </tr>
                <tr>
                    <td>
                        <button type="submit" class="btn btn-sm btn-primary">UPDATE</button>
                    </td>
                </tr>
                
            </table>
        </form>
    </div>
{% endblock %}