apotek/urls.py
from django.contrib import admin
from django.urls import path
from apotek import views

app_name = 'apotek'
urlpatterns = [
    path('', views.list_apotek, name ='list_apotek'),
    path('produk/', views.list_produk_apotek, name ='list_produk_apotek'),
    path('delete/<id>', views.delete_apotek, name ='delete_apotek'),
    path('produk/delete/<id_apotek>/<id_produk>', views.delete_produk_apotek, name ='delete_produk_apotek'),
    path('update/<id>', views.update_apotek, name ='to_update_apotek'),
    path('produk/update/<id_apotek>/<id_produk>', views.update_produk_apotek,
         name ='to_update_produk_apotek'),
    path('create/', views.create_apotek, name ='create_apotek'),
    path('produk/create/', views.create_produk_apotek, name ='create_produk_apotek'),
    path('produk/avlble/<id>', views.id_produk_choices, name = 'id_produk_choice')
]

balai_pengobatan/urls.py
from django.urls import path
from . import views


app_name = 'balai_pengobatan'

urlpatterns = [
    path('', views.balai, name="index"),
    path('create_balai', views.create_balai, name="create_balai"),
    path('delete_balai/<id>', views.delete_balai, name ='delete_balai'),
    path('update_balai/<id>', views.update_balai, name="update_balai"),
    path('obat', views.obat, name="obat"),
    path('obat/create_obat', views.create_obat, name="create_obat"),
    path('obat/update_obat/<id>', views.update_obat, name="update_obat"),
    path('obat/delete_obat/<id>', views.delete_obat, name="delete_obat")
]

list_produk_pengantaran/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'list_produk_pengantaran'

urlpatterns = [
	path('list_produk_dibeli/',views.list_produk_dibeli,name='list_produk_dibeli'),
    path('create_list_produk_dibeli/',views.create_list_produk_dibeli,name='create_list_produk_dibeli'),
    path('pengantaran_farmasi/',views.pengantaran_farmasi,name='pengantaran_farmasi'),
    path('create_pengantaran_farmasi/',views.create_pengantaran_farmasi,name='create_pengantaran_farmasi'),
    path('delete/<id>', views.delete_pengantaran_farmasi, name ='delete_pengantaran_farmasi'),
    path('produk/delete/<id_apotek>/<id_produk>/<id_transaksi_pembelian>', views.delete_list_produk_dibeli, name ='delete_list_produk_dibeli'),
    path('update_pengantaran_farmasi/<id>', views.update_pengantaran_farmasi, name ='update_pengantaran_farmasi'),
    path('update_list_produk_dibeli/<id_apotek>/<id_produk>/<id_transaksi_pembelian>', views.update_list_produk_dibeli,
         name ='update_list_produk_dibeli'),
    path('apotek/avlble/<id>', views.id_apotek_choices, name = 'id_apotek_choice')
]

login_register/urls.py
from django.urls import path
from . import views

app_name = 'login_register'

urlpatterns = [
    path('', views.home, name='landingpage'),
    path('login/', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('homepage/', views.homepage, name='homepage'),
    path('register/kurir/', views.kurir, name='kurir'),
    path('register/konsumen/', views.konsumen, name='konsumen'),
    path('register/admin-apotek/', views.admin_apotek, name='admin_apotek'),
    path('register/cs/', views.cs, name='cs'),
    path('logout/', views.logout, name="logout")
]

tk_basdat_43/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('login_register.urls')),
    path('transaksi_pembelian/', include('transaksi_pembelian.urls')),
    path('list_produk_pengantaran/',include('list_produk_pengantaran.urls', namespace = 'list_produk_pengantaran')),
    path('balai_pengobatan/', include('balai_pengobatan.urls')),
    path('apotek/', include('apotek.urls')),
]

transaksi_pembelian/urls.py
from django.urls import path
from . import views

app_name = 'transaksi_pembelian'

urlpatterns = [
    path('daftar_transaksi_pembelian/', views.daftar, name='daftar'),
    path('update_transaksi_pembelian/<id_transaksi_pembelian>/<waktu_pembelian>/<total_pembayaran>', views.update, name='update'),
    path('create_transaksi_pembelian/', views.create, name='create'),
    path('profil_pengguna/', views.profile, name='profil'),
    path('delete_transaksi_pembelian/<id_transaksi_pembelian>', views.delete, name='delete'),
]

login_register/models.py
from django.db import models

# Create your models here.

login_register/forms.py
from django import forms
import re


class LoginForm(forms.Form):
    username = forms.EmailField(label='Username:', max_length=50)
    password = forms.CharField(label='Password:', max_length=200, widget=forms.PasswordInput)


class AdminApotekForm(forms.Form):
    email = forms.EmailField(label='Email', max_length=50)
    password = forms.CharField(label='Password', max_length=200, widget=forms.PasswordInput)
    nama_lengkap = forms.CharField(label='Nama Lengkap', max_length=50)
    no_telepon = forms.CharField(label='No Telepon', max_length=20)

    def clean(self):
        cd = self.cleaned_data
        email = cd.get("email")
        password = cd.get("password")
        nama_lengkap = cd.get("nama_lengkap")
        no_telepon = cd.get("no_telepon")

        if not bool(re.search('^\d{3} \d{3} \d{4}$', str(no_telepon))):
            self.add_error("no_telepon", "Wrong No Telp Apotek Format {XXX XXX XXXX}")

        return cd


class KurirForm(AdminApotekForm):
    nama_perusahaan = forms.CharField(label='Nama Perusahaan', max_length=50)


class KonsumenForm(AdminApotekForm):
    jenis_kelamin = forms.CharField(label='Jenis Kelamin', max_length=1)
    tanggal_lahir = forms.DateField(label='Waktu', widget=forms.DateInput(attrs={'type':'date'}))

    def clean(self):
        super().clean()
        cd = self.cleaned_data
        jenis_kelamin = cd.get("jenis_kelamin")
        tanggal_lahir = cd.get("tanggal_lahir")

        if jenis_kelamin != 'M' and jenis_kelamin != 'F':
            self.add_error("jenis_kelamin", "Jenis Kelamin F/M")

        return cd


class CSForm(AdminApotekForm):
    no_ktp = forms.CharField(label='No KTP', max_length=50)
    no_sia = forms.CharField(label='No SIA', max_length=50)

    def clean(self):
        super().clean()

        cd = self.cleaned_data
        no_ktp = cd.get("no_ktp")
        no_sia = cd.get("no_sia")

        if re.search('[\D]', str(no_sia)):
            self.add_error('no_sia', "No SIA contains Non-Digit character")

        if re.search('[\D]', str(no_ktp)):
            self.add_error('no_ktp', "No KTP contains Non-Digit character")

        return cd


class AlamatForm(forms.Form):
    status_alamat = forms.CharField(label='Alamat', required=False, widget=forms.TextInput(attrs={'placeholder': 'Status Alamat'}))
    alamat = forms.CharField(label='', required=False, widget=forms.TextInput(attrs={'placeholder': 'Alamat'}))

    def clean(self):
        raw = dict(self.data)
        alamat = raw["alamat"]
        status_alamat = raw["status_alamat"]

        if len(set(alamat)) != len(alamat):
            self.add_error("alamat", "Duplicate Alamat")

        if "" in alamat:
            self.add_error("alamat", "Null Alamat Input")

        if "" in status_alamat:
            self.add_error("status_alamat", "Null Status Alamat Input")

        self.cleaned_data["alamat"] = alamat
        self.cleaned_data["status_alamat"] = status_alamat

        return self.cleaned_data

login_register/views.py
from django.shortcuts import render, redirect
from django.db import connection, utils
from .forms import LoginForm, KurirForm, KonsumenForm, AlamatForm, AdminApotekForm, CSForm
from apotek.views import get_apotek_choices
from random import choice
from .decorators import *
# Create your views here.


def dictfetchall(cursor):
    columns = [col[0] for col in cursor.description]
    return [
        dict(zip(columns, row))
        for row in cursor.fetchall()
    ]


@no_login
def home(request):
    return render(request, 'landingpage.html')


@no_login
def login(request):
    with connection.cursor() as cursor:
        if request.method =='POST':
            form = LoginForm(request.POST)

            if form.is_valid():
                username = form.cleaned_data["username"]
                password = form.cleaned_data["password"]

                cursor.execute("SELECT * FROM pengguna WHERE " +
                               "email = %s AND password = %s", [username, password])

                user = dictfetchall(cursor)

                if len(user) != 0:
                    user = user[0]
                    email = user["email"]
                    request.session["email"] = email
                    request.session["nama_lengkap"] = user["nama_lengkap"]
                    request.session["logged_in"] = True

                    if check_role(email, "konsumen"):
                        request.session["role"] = "KONSUMEN"

                    elif check_role(email, "admin_apotek"):
                        request.session["role"] = "ADMIN_APOTEK"

                    elif check_role(email, "kurir"):
                        request.session["role"] = "KURIR"

                    elif check_role(email, "cs"):
                        request.session["role"] = "CS"

                    print(dict(request.session))
                    return redirect("login_register:homepage")

                return redirect("login_register:login")
        else:
            form = LoginForm()
            args = {'form': form}
            return render(request, 'login.html', args)


@no_login
def register(request):
    return render(request, 'register.html')


@login_required
def homepage(request):
    return render(request, 'homepage.html')


@no_login
def kurir(request):
    form1 = KurirForm()

    if request.method == "GET":
        return render(request, 'kurir.html', {'form':form1})

    elif request.method == "POST":
        with connection.cursor() as cursor:
            form = KurirForm(request.POST)
            if form.is_valid():
                try:
                    create_pengguna(form)
                    email = form.cleaned_data.get("email")

                    cursor.execute("SELECT id_kurir FROM kurir ORDER BY id_kurir DESC LIMIT 1")
                    id_kurir = dictfetchall(cursor)[0]["id_kurir"]
                    id_kurir = str(int(id_kurir) + 1)

                    nama_perusahaan = form.cleaned_data.get("nama_perusahaan")

                    query = "INSERT INTO kurir(id_kurir, email, " \
                            "nama_perusahaan) " \
                            "VALUES(%s, %s, %s);"

                    cursor.execute(query, [id_kurir, email, nama_perusahaan])

                except utils.IntegrityError as e:
                    delete_user_table(email, "kurir")
                    delete_user_table(email, "pengguna")
                    return render(request, 'kurir.html',
                                  {'form': form1, "message": str(e)})

                return redirect("login_register:login")

            return render(request, 'kurir.html',
                          {'form': form1, "form1": form})


@no_login
def konsumen(request):
    form1 = KonsumenForm()
    form2 = AlamatForm()

    if request.method == "GET":
        return render(request, 'konsumen.html', {'form1':form1, 'form2':form2})

    elif request.method == "POST":
        with connection.cursor() as cursor:
            new_form1 = KonsumenForm(request.POST)
            new_form2 = AlamatForm(request.POST)
            if new_form1.is_valid() and new_form2.is_valid():
                try:
                    create_pengguna(new_form1)
                    email = new_form1.cleaned_data.get("email")

                    jenis_kelamin = new_form1.cleaned_data.get("jenis_kelamin")
                    tanggal_lahir = new_form1.cleaned_data.get("tanggal_lahir")
                    cursor.execute("SELECT id_konsumen FROM konsumen ORDER BY id_konsumen DESC LIMIT 1")
                    id_konsumen = dictfetchall(cursor)[0]["id_konsumen"]
                    id_konsumen = str(int(id_konsumen) + 1)

                    query = "INSERT INTO konsumen(id_konsumen, email, " \
                            "jenis_kelamin, tanggal_lahir) " \
                            "VALUES(%s, %s, %s, %s);"

                    cursor.execute(query, [id_konsumen, email, jenis_kelamin, tanggal_lahir])

                    alamat = new_form2.cleaned_data["alamat"]
                    status_alamat = new_form2.cleaned_data["status_alamat"]

                    query = "INSERT INTO alamat_konsumen(id_konsumen, alamat, " \
                            "status) " \
                            "VALUES(%s, %s, %s);"

                    for ii in range(len(alamat)):
                        cursor.execute(query, [id_konsumen, alamat[ii], status_alamat[ii]])

                except utils.IntegrityError as e:
                    delete_user_table(id_konsumen, "alamat_konsumen")
                    delete_user_table(email, "konsumen")
                    delete_user_table(email, "pengguna")
                    return render(request, "apotek/create_apotek.html",
                                  {'form1': form1, 'form2': form2,
                                   "message": str(e)})

                return redirect("login_register:login")

            return render(request,
                          'konsumen.html',
                          {'form1': form1, 'form2': form2,
                           'form1_errors': new_form1.errors,
                           'form2_errors': new_form2.errors})


@no_login
def admin_apotek(request):
    form1 = AdminApotekForm()
    if request.method == "GET":
        return render(request, 'admin_apotek.html', {'form':form1})

    elif request.method == "POST":
        with connection.cursor() as cursor:
            form = AdminApotekForm(request.POST)

            if form.is_valid():
                try:
                    create_pengguna(form)
                    email = form.cleaned_data.get("email")

                    query = "INSERT INTO apoteker(email)" \
                            "VALUES(%s);"
                    cursor.execute(query, [email])

                    list_id_apotek = get_apotek_choices()
                    id_apotek = choice(list_id_apotek)

                    query = "INSERT INTO admin_apotek(email, id_apotek)" \
                            "VALUES(%s, %s);"

                    cursor.execute(query, [email, id_apotek])

                except utils.IntegrityError as e:
                    delete_user_table(email, "admin_apotek")
                    delete_user_table(email, "apoteker")
                    delete_user_table(email, "pengguna")
                    return render(request, 'admin_apotek.html',
                                  {'form': form1, "message": str(e)})

                return redirect("login_register:login")

            return render(request, 'admin_apotek.html',
                          {'form':form1, "form1": form})


@no_login
def cs(request):
    form1 = CSForm()
    if request.method == "GET":
        return render(request, 'CS.html', {'form':form1})

    elif request.method == "POST":
        form = CSForm(request.POST)
        with connection.cursor() as cursor:

            if form.is_valid():
                try:
                    create_pengguna(form)
                    email = form.cleaned_data.get("email")

                    query = "INSERT INTO apoteker(email)" \
                            "VALUES(%s);"
                    cursor.execute(query, [email])

                    no_ktp = form.cleaned_data.get("no_ktp")
                    no_sia = form.cleaned_data.get("no_sia")

                    query = "INSERT INTO cs(no_ktp, email, no_sia)" \
                            "VALUES(%s, %s, %s);"

                    cursor.execute(query, [no_ktp, email, no_sia])

                except utils.IntegrityError as e:
                    delete_user_table(email, "cs")
                    delete_user_table(email, "apoteker")
                    delete_user_table(email, "pengguna")
                    return render(request, 'CS.html',
                                  {'form': form1, "message": str(e)})

                return redirect("login_register:login")

            return render(request, 'CS.html',
                          {'form': form1, "form1": form})


def check_role(id, role):
    with connection.cursor() as cursor:
        query = "SELECT * FROM " + role + " WHERE email = %s"
        cursor.execute(query, [id])

        row = dictfetchall(cursor)

        if len(row) != 0:
            return True
        else:
            return False


def delete_user_table(id, table):
    with connection.cursor() as cursor:
        query = ""
        if table == "alamat_konsumen":
            query = "DELETE FROM alamat_konsumen WHERE id_konsumen = %s"
        else:
            query = "DELETE FROM " + table + " WHERE email = %s"

        cursor.execute(query, [id])


def create_pengguna(form):
    with connection.cursor() as cursor:
        cd = form.cleaned_data
        email = cd.get("email")
        password = cd.get("password")
        nama_lengkap = cd.get("nama_lengkap")
        no_telepon = cd.get("no_telepon")

        query = "INSERT INTO pengguna(email, telepon, " \
                "password, nama_lengkap) " \
                "VALUES(%s, %s, %s, %s);"

login_register/templates/CS.html
{% extends 'base_no_login.html' %}

{% block title %}
    <title>Pendaftaran CS</title>
{% endblock %}

{% block content %}
<div>
    <h1>FORM PENDAFTARAN CS</h1>
</div>
{% if form1 or message %}
    <div class="alert alert-danger" role="alert">
        <ul>
        {% if form1 %}
            {% for field, errors in form1.errors.items %}
                {% for error in errors %}
                    <li>{{ error }}</li>
                {% endfor %}
            {% endfor %}
        {% endif %}
        {% if message %}
            <li>{{ message }}</li>
        {% endif %}
        </ul>
    </div>
{% endif %}
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">DAFTAR</button>
</form>
{% endblock %}

login_register/templates/admin_apotek.html
{% extends 'base_no_login.html' %}

{% block title %}
    <title>Pendafatarn Admin Apotek</title>
{% endblock %}

{% block content %}
    <h1>PENDAFTARAN ADMIN APOTEK</h1>
    {% if form1 or message %}
    <div class="alert alert-danger" role="alert">
        <ul>
        {% if form1 %}
            {% for field, errors in form1.errors.items %}
                {% for error in errors %}
                    <li>{{ error }}</li>
                {% endfor %}
            {% endfor %}
        {% endif %}
        {% if message %}
            <li>{{ message }}</li>
        {% endif %}
        </ul>
    </div>
    {% endif %}
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">DAFTAR</button>
    </form>
{% endblock %}

login_register/templates/homepage.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'homepage.css' %}">
    <title>Homepage</title>
</head>
<body>
    <div>
        <h1>Welcome to Farmakami</h1>
    </div>
    <div class="ml-2">
        <a href="{% url 'login_register:logout' %}">
          <button class="btn btn-danger my-2 my-sm-0" type="button">Logout</button>
        </a>
    </div>
    <div class="dropdown">
        <button type="button" class="btn btn-secondary btn-block dropdown-toggle" data-toggle="dropdown">
          Profil
        </button>
        <div class="dropdown-menu buttondrop">
            <a class="dropdown-item" href="{% url 'transaksi_pembelian:profil' %}">Profil Pengguna</a>
        </div>
      </div>
    <div class="dropdown">
      <button type="button" class="btn btn-secondary btn-block dropdown-toggle" data-toggle="dropdown">
        Balai Pengobatan & Apotek
      </button>
      <div class="dropdown-menu buttondrop">
        <a class="dropdown-item" href="{% url 'apotek:list_apotek' %}">Daftar Apotek</a>
        {% if request.session.role == "ADMIN_APOTEK" %}
        <a class="dropdown-item" href="{% url 'apotek:create_apotek' %}">Create Apotek</a>
        {% endif %}
        <a class="dropdown-item" href="{% url 'balai_pengobatan:index' %}">Daftar Balai Pengobatan</a>
        {% if request.session.role == "ADMIN_APOTEK" %}
        <a class="dropdown-item" href="{% url 'balai_pengobatan:create_balai' %}">Create Balai Pengobatan</a>
        {% endif %}
      </div>
    </div>
    <div class="dropdown">
      <button type="button" class="btn btn-secondary btn-block dropdown-toggle" data-toggle="dropdown">
        Transaksi
      </button>
      <div class="dropdown-menu buttondrop">
        <a class="dropdown-item" href="{% url 'transaksi_pembelian:daftar' %}">Daftar Transaksi Pembelian</a>
        {% if request.session.role == "ADMIN_APOTEK" %}
        <a class="dropdown-item" href="{% url 'transaksi_pembelian:create' %}">Create Transaksi Pembelian</a>
        {% endif %}
      </div>
    </div>
    <div class="dropdown">
        <button type="button" class="btn btn-secondary btn-block dropdown-toggle" data-toggle="dropdown">
          Produk Apotek
        </button>
        <div class="dropdown-menu buttondrop">
          {% if request.session.role == "ADMIN_APOTEK" %}
          <a class="dropdown-item" href="{% url 'apotek:create_produk_apotek' %}">Create Produk Apotek</a>
          {% endif %}
          <a class="dropdown-item" href="{% url 'apotek:list_produk_apotek' %}">Daftar Produk Apotek</a>
        </div>
      </div>
      <div class="dropdown">
        <button type="button" class="btn btn-secondary btn-block dropdown-toggle" data-toggle="dropdown">
          Produk Dibeli
        </button>
        <div class="dropdown-menu buttondrop">
          {% if request.session.role == "ADMIN_APOTEK" %}
          <a class="dropdown-item" href="{% url 'list_produk_pengantaran:create_list_produk_dibeli' %}">Create Produk Dibeli</a>
          {% endif %}
          <a class="dropdown-item" href="{% url 'list_produk_pengantaran:list_produk_dibeli' %}">Daftar Produk Dibeli</a>
        </div>
      </div>
      <div class="dropdown">
        <button type="button" class="btn btn-secondary btn-block dropdown-toggle" data-toggle="dropdown">
          Pengantaran
        </button>
        <div class="dropdown-menu buttondrop">
          {% if request.session.role == "ADMIN_APOTEK" %}
          <a class="dropdown-item" href="{% url 'list_produk_pengantaran:create_pengantaran_farmasi' %}">Create Pengantaran Farmasi</a>
          {% endif %}
          <a class="dropdown-item" href="{% url 'list_produk_pengantaran:pengantaran_farmasi' %}">Daftar Pengantaran Farmasi</a>
        </div>
      </div>
      <div class="dropdown">
        <button type="button" class="btn btn-secondary btn-block dropdown-toggle" data-toggle="dropdown">
          Obat
        </button>
        <div class="dropdown-menu buttondrop">
          <a class="dropdown-item" href="{% url 'balai_pengobatan:obat' %}">Daftar Obat</a>
          {% if request.session.role == "ADMIN_APOTEK" or request.session.role == "CS" %}
          <a class="dropdown-item" href="{% url 'balai_pengobatan:create_obat' %}">Create Obat</a>
          {% endif %}
        </div>
      </div>
</body>
</html>

login_register/templates/konsumen.html
{% extends 'base_no_login.html' %}
{% block title %}
    <title>Pendaftaran Konsumen</title>
{% endblock %}

{% block content %}
<div>
    <h1>FORM PENDAFTARAN KONSUMEN</h1>
</div>
{% if form1_errors or form2_errors or message %}
    <div class="alert alert-danger" role="alert">
        <ul>
        {% if form1_errors %}
            {% for field, errors in form1_errors.items %}
                {% for error in errors %}
                    <li>{{ error }}</li>
                {% endfor %}
            {% endfor %}
        {% endif %}
        {% if form2_errors %}
            {% for field, errors in form2_errors.items %}
                {% for error in errors %}
                    <li>{{ error }}</li>
                {% endfor %}
            {% endfor %}
        {% endif %}
        {% if message %}
            <li>{{ message }}</li>
        {% endif %}
        </ul>
    </div>
{% endif %}
<form method="POST">
    {% csrf_token %}
    {{ form1.as_p }}
    <div id="list-alamat">
        {{ form2 }}
    </div>
    <button type="button" onclick="addAlamat()">Tambah Alamat</button>
    <button type="submit">DAFTAR</button>
</form>
{% endblock %}

{% block script %}
<script>
    let count = 1
    function addAlamat() {
        count++;
        const listAlamat = document.getElementById("list-alamat")
        const container = document.createElement("div")
        container.id=`alamat-${count}-container`
        container.innerHTML=`
            <button type="button" onclick="removeAlamat(${count})" id="alamat-${count}">Remove</button>
            <input type="text" name="status_alamat" id="alamat-${count}-input" placeholder="Status Alamat">
            <input type="text" name="alamat" placeholder="Alamat">
        `
        listAlamat.appendChild(container)
    }
    function removeAlamat(id) {
        const listAlamat = document.getElementById("list-alamat")
        if(listAlamat.children.length > 1){
             const container = document.getElementById(`alamat-${id}-container`)
            listAlamat.removeChild(container);
        }
    }
</script>
{% endblock %}

login_register/templates/kurir.html
{% extends 'base_no_login.html' %}

{% block title %}
    <title>Pendaftaran Kurir</title>
{% endblock %}

{% block content %}
<div>
    <h1>FORM PENDAFTARAN KURIR</h1>
</div>
{% if form1 or message %}
    <div class="alert alert-danger" role="alert">
        <ul>
        {% if form1 %}
            {% for field, errors in form1.errors.items %}
                {% for error in errors %}
                    <li>{{ error }}</li>
                {% endfor %}
            {% endfor %}
        {% endif %}
        {% if message %}
            <li>{{ message }}</li>
        {% endif %}
        </ul>
    </div>
{% endif %}
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">DAFTAR</button>
</form>
{% endblock %}

login_register/templates/landingpage.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Farmakami</title>
</head>
<body>
    <div>
        <h1>Farmakami</h1>
        <p>please login to continue or register</p>
    </div>
    <div>
        <a href="{% url 'login_register:login' %}"><button>LOGIN</button></a>
        <a href="{% url 'login_register:register' %}"><button>REGISTER</button></a>
    </div>
</body>
</html>

login_register/templates/login.html
{% extends 'base_no_login.html' %}

{% load static %}
{% block title %}
<title>Login</title>
{% endblock %}



{% block content %}
<div>
    <h1>Login</h1>
    <p>Login using valid email</p>
</div>
<div>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">SUBMIT</button>
    </form>
</div>
{% endblock %}

login_register/templates/register.html
{% extends 'base_no_login.html' %}

{% block title %}
    <title>Register</title>
{% endblock %}

{% block content %}
    <div>
        <h1>Register</h1>
    </div>
    <div class="mb-2 mt-2">
    <a href="{% url 'login_register:admin_apotek' %}">
          <button type="button" class="btn btn-sm btn-primary">Register Admin Apotek</button>
    </a>
    <a href="{% url 'login_register:konsumen' %}">
          <button type="button" class="btn btn-sm btn-primary">Register Konsumen</button>
    </a>
    <a href="{% url 'login_register:kurir' %}">
          <button type="button" class="btn btn-sm btn-primary">Register Kurir</button>
    </a>
    <a href="{% url 'login_register:cs' %}">
          <button type="button" class="btn btn-sm btn-primary">Register CS</button>
    </a>
    </div>
{% endblock %}