apotek/urls.py
from django.contrib import admin
from django.urls import path
from apotek import views

app_name = 'apotek'
urlpatterns = [
    path('', views.list_apotek, name ='list_apotek'),
    path('produk/', views.list_produk_apotek, name ='list_produk_apotek'),
    path('delete/<id>', views.delete_apotek, name ='delete_apotek'),
    path('produk/delete/<id_apotek>/<id_produk>', views.delete_produk_apotek, name ='delete_produk_apotek'),
    path('update/<id>', views.update_apotek, name ='to_update_apotek'),
    path('produk/update/<id_apotek>/<id_produk>', views.update_produk_apotek,
         name ='to_update_produk_apotek'),
    path('create/', views.create_apotek, name ='create_apotek'),
    path('produk/create/', views.create_produk_apotek, name ='create_produk_apotek'),
    path('produk/avlble/<id>', views.id_produk_choices, name = 'id_produk_choice')
]

list_produk_pengantaran/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'list_produk_pengantaran'

urlpatterns = [
	path('list_produk_dibeli/',views.list_produk_dibeli,name='list_produk_dibeli'),
    path('create_list_produk_dibeli/',views.create_list_produk_dibeli,name='create_list_produk_dibeli'),
    path('pengantaran_farmasi/',views.pengantaran_farmasi,name='pengantaran_farmasi'),
    path('create_pengantaran_farmasi/',views.create_pengantaran_farmasi,name='create_pengantaran_farmasi'),
    path('delete/<id>', views.delete_pengantaran_farmasi, name ='delete_pengantaran_farmasi'),
    path('produk/delete/<id_apotek>/<id_produk>/<id_transaksi_pembelian>', views.delete_list_produk_dibeli, name ='delete_list_produk_dibeli'),
    path('update_pengantaran_farmasi/<id>', views.update_pengantaran_farmasi, name ='update_pengantaran_farmasi'),
    path('update_list_produk_dibeli/<id_apotek>/<id_produk>/<id_transaksi_pembelian>', views.update_list_produk_dibeli,
         name ='update_list_produk_dibeli'),
    path('apotek/avlble/<id>', views.id_apotek_choices, name = 'id_apotek_choice')
]

tk_basdat_43/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('login_register.urls')),
    path('transaksi_pembelian/', include('transaksi_pembelian.urls')),
    path('list_produk_pengantaran/',include('list_produk_pengantaran.urls', namespace = 'list_produk_pengantaran')),
    path('balai_pengobatan/', include('balai_pengobatan.urls')),
    path('apotek/', include('apotek.urls')),
]

list_produk_pengantaran/models.py
from django.db import models

# Create your models here.

list_produk_pengantaran/forms.py
from django import forms

class CreateLPDForm(forms.Form):
    id_produk = forms.CharField(max_length=10)
    id_apotek = forms.CharField(max_length=10)
    id_transaksi = forms.CharField(max_length=10)
    jumlah = forms.IntegerField()

    def clean(self):
        cd = self.cleaned_data
        id_produk = cd.get("id_produk")
        id_apotek = cd.get("id_apotek")
        id_transaksi = cd.get("id_transaksi")
        jumlah = cd.get("jumlah")
        
        return cd

class UpdateLPDForm(forms.Form):
    id_transaksi_pembelian = forms.CharField(max_length=10)
    jumlah = forms.IntegerField()

    def clean(self):
        cd = self.cleaned_data
        id_transaksi_pembelian = cd.get("id_transaksi_pembelian")
        jumlah = cd.get("jumlah")
        
        return cd

class CreatePFForm(forms.Form):
    id_transaksi = forms.CharField(max_length=10)
    waktu = forms.CharField()
    biaya_kirim = forms.IntegerField()

    def clean(self):
        cd = self.cleaned_data
        id_transaksi = cd.get("id_transaksi")
        waktu = cd.get("waktu")
        biaya_kirim = cd.get("biaya_kirim")
        
        return cd

class UpdatePFForm(forms.Form):
    waktu = forms.CharField()
    status = forms.CharField(max_length=20)
    biaya_kirim = forms.IntegerField()

    def clean(self):
        cd = self.cleaned_data
        status = cd.get("status")
        waktu = cd.get("waktu")
        biaya_kirim = cd.get("biaya_kirim")
        
        return cd

list_produk_pengantaran/views.py
from django.shortcuts import render, redirect
from django.db import connection, utils
from django.http import JsonResponse
from .forms import CreateLPDForm, UpdateLPDForm, CreatePFForm, UpdatePFForm
from login_register.decorators import *
import datetime

# Create your views here.
def dictfetchall(cursor):
    columns = [col[0] for col in cursor.description]
    return [
        dict(zip(columns, row))
        for row in cursor.fetchall()
    ]

@login_required
def list_produk_dibeli(request):
    with connection.cursor() as cursor:
        cursor.execute("SELECT * FROM list_produk_dibeli")
        rows = dictfetchall(cursor)
        return render(request, 'list_produk_pengantaran/list_produk_dibeli.html', {'content': rows})

@login_required
@admin_required
def update_list_produk_dibeli(request, id_apotek, id_produk, id_transaksi_pembelian):
    with connection.cursor() as cursor:
        list_id_transaksi_pembelian = get_id_transaksi_pembelian_choices()

        if request.method == "GET":
            list_id_transaksi_pembelian = get_id_transaksi_pembelian_choices()
            cursor.execute("SELECT * FROM list_produk_dibeli WHERE id_apotek = %s AND id_produk = %s AND id_transaksi_pembelian = %s"
                           , [id_apotek, id_produk, id_transaksi_pembelian])
            row = dictfetchall(cursor)[0]
            return render(request, 'list_produk_pengantaran/update_list_produk_dibeli.html',
                           {'data': row, 'list_id_transaksi_pembelian':list_id_transaksi_pembelian})

        elif request.method == "POST":
            form = UpdateLPDForm(request.POST)
            data = dict(map(lambda kv: (kv[0], kv[1][0]), dict(request.POST).items()))
            if form.is_valid():
                cd = form.cleaned_data
                id_transaksi_pembelian_new = cd.get("id_transaksi_pembelian")
                jumlah = cd.get("jumlah")
                
                query = "UPDATE list_produk_dibeli SET id_transaksi_pembelian = %s, " \
                        "jumlah = %s WHERE id_apotek = %s AND id_produk = %s AND id_transaksi_pembelian = %s"

                try:
                    cursor.execute(query, [id_transaksi_pembelian_new, jumlah,
                                           id_apotek, id_produk, id_transaksi_pembelian])

                except utils.IntegrityError as e:
                    return render(request, 'list_produk_pengantaran/update_list_produk_dibeli.html', {"data": data,
                                    'list_id_transaksi_pembelian':list_id_transaksi_pembelian, "message" : str(e)})
                return redirect("list_produk_pengantaran:list_produk_dibeli")

            return render(request, 'list_produk_pengantaran/update_list_produk_dibeli.html',
                          {"data": data, 'list_id_transaksi_pembelian':list_id_transaksi_pembelian, "form" : form})

@login_required
@admin_required
def delete_list_produk_dibeli(request, id_apotek, id_produk, id_transaksi_pembelian):
    with connection.cursor() as cursor:
        cursor.execute("DELETE FROM list_produk_dibeli WHERE id_apotek = %s AND id_produk = %s AND id_transaksi_pembelian = %s", [id_apotek, id_produk, id_transaksi_pembelian])
        return redirect('list_produk_pengantaran:list_produk_dibeli')

@login_required
@admin_required
def create_list_produk_dibeli(request):
    with connection.cursor() as cursor:
        list_id_produk = get_produk_choices()
        list_id_transaksi = get_id_transaksi_pembelian_choices()

        if request.method == "GET":
            list_id_apotek = id_apotek_choices_raw(list_id_produk[0])
            return render(request, "list_produk_pengantaran/create_list_produk_dibeli.html",
                          {"list_id_apotek": list_id_apotek,
                           "list_id_produk": list_id_produk, 'list_id_transaksi': list_id_transaksi})

        elif request.method == "POST":
            form = CreateLPDForm(request.POST)
            data = dict(map(lambda kv: (kv[0], kv[1][0]), dict(request.POST).items()))
            list_id_apotek = id_apotek_choices_raw(data["id_produk"])

            if form.is_valid():
                cd = form.cleaned_data
                id_produk = cd.get("id_produk")
                id_apotek = cd.get("id_apotek")
                id_transaksi = cd.get("id_transaksi")
                jumlah = cd.get("jumlah")

                query = "INSERT INTO list_produk_dibeli(id_apotek, id_produk, id_transaksi_pembelian, jumlah) " \
                        "VALUES(%s, %s, %s, %s);"
                try:
                    cursor.execute(query, [id_apotek, id_produk, id_transaksi, jumlah])

                except utils.IntegrityError as e:
                    return render(request, 'list_produk_pengantaran/create_list_produk_dibeli.html',
                                  {"data": data, "list_id_apotek": list_id_apotek,
                                   "list_id_produk": list_id_produk, 'list_id_transaksi': list_id_transaksi,
                                   "message": str(e)})

                return redirect("list_produk_pengantaran:list_produk_dibeli")

            return render(request, "list_produk_pengantaran/create_list_produk_dibeli.html",
                          {"data": data, 'form': form,
                           "list_id_apotek": list_id_apotek, 'list_id_transaksi': list_id_transaksi,
                           "list_id_produk": list_id_produk})

@login_required
def pengantaran_farmasi(request):
    with connection.cursor() as cursor:
        cursor.execute("SELECT * FROM pengantaran_farmasi")
        rows = dictfetchall(cursor)
        return render(request, 'list_produk_pengantaran/pengantaran_farmasi.html', {'content': rows})

@login_required
@admin_required
def update_pengantaran_farmasi(request, id):
    with connection.cursor() as cursor:
        if request.method == "GET":
            cursor.execute("SELECT * FROM pengantaran_farmasi WHERE id_pengantaran = %s", [id])
            row = dictfetchall(cursor)[0]
            return render(request, 'list_produk_pengantaran/update_pengantaran_farmasi.html', {"data": row})
        elif request.method == "POST":
            form = UpdatePFForm(request.POST)
            data = dict(map(lambda kv: (kv[0], kv[1][0]), dict(request.POST).items()))
            if form.is_valid():
                cd = form.cleaned_data
                waktu = cd.get("waktu")
                status = cd.get("status")
                biaya_kirim = cd.get("biaya_kirim")

                now = datetime.datetime.now().strftime('%H:%M')
                waktu_db = str(waktu) + " " + now
                
                query = "UPDATE pengantaran_farmasi SET waktu = %s, "\
                        "status_pengantaran = %s, biaya_kirim = %s WHERE id_pengantaran = %s"

                try:
                    cursor.execute(query, [waktu_db, status, biaya_kirim, id])
                except utils.IntegrityError as e:
                    return render(request, 'list_produk_pengantaran/update_pengantaran_farmasi.html', {"data": data,
                                                                         "message" : str(e)})

                return redirect("list_produk_pengantaran:pengantaran_farmasi")

            return render(request, 'list_produk_pengantaran/update_pengantaran_farmasi.html', {"data": data, "form" : form})

@login_required
@admin_required
def delete_pengantaran_farmasi(request, id):
    with connection.cursor() as cursor:
        cursor.execute("DELETE FROM pengantaran_farmasi WHERE id_pengantaran = %s", [id])
        return redirect('list_produk_pengantaran:pengantaran_farmasi')

@login_required
@admin_required
def create_pengantaran_farmasi(request):
    with connection.cursor() as cursor:
        list_id_transaksi = get_id_transaksi_pengantaran()
        if request.method == "GET":
            return render(request, "list_produk_pengantaran/create_pengantaran_farmasi.html",
                            {'list_id_transaksi': list_id_transaksi})
        elif request.method == "POST":
            form = CreatePFForm(request.POST)
            if form.is_valid():
                cursor.execute("SELECT id_pengantaran::INTEGER FROM pengantaran_farmasi ORDER BY id_pengantaran desc LIMIT 1")
                id_pengantaran = dictfetchall(cursor)[0]["id_pengantaran"]
                id_pengantaran = str(int(id_pengantaran) + 1)

                cd = form.cleaned_data
                id_transaksi = cd.get("id_transaksi")
                waktu = cd.get("waktu")
                biaya_kirim = cd.get("biaya_kirim")

                now = datetime.datetime.now().strftime('%H:%M')
                waktu_db = str(waktu) + " " + now
                
                query = "INSERT INTO pengantaran_farmasi(id_pengantaran,id_kurir,id_transaksi_pembelian," \
                        "waktu,status_pengantaran,biaya_kirim, total_biaya) " \
                        "VALUES(%s, '2', %s, %s, 'Picked Up', %s, '0');"

                try:
                    cursor.execute(query, [id_pengantaran, id_transaksi, waktu_db, biaya_kirim])
                except utils.IntegrityError as e:
                    return render(request, "list_produk_pengantaran/create_pengantaran_farmasi.html", 
                                    {"message" : str(e), 'list_id_transaksi': list_id_transaksi})

                return redirect("list_produk_pengantaran:pengantaran_farmasi")

            return render(request, "list_produk_pengantaran/create_pengantaran_farmasi.html", 
                            {"form" : form, 'list_id_transaksi': list_id_transaksi})

def get_id_transaksi_pembelian_choices():
    with connection.cursor() as cursor:
        cursor.execute("SELECT id_transaksi_pembelian FROM transaksi_pembelian")
        transaksi_cursor = dictfetchall(cursor)

        id_transaksi_pembelian = []

        for row in transaksi_cursor:
            id_transaksi_pembelian.append(row['id_transaksi_pembelian'])

list_produk_pengantaran/templates/list_produk_pengantaran/create_list_produk_dibeli.html
{% extends 'base_with_login.html' %}{% load static  %}

{% block cssJs %}
<link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous" />
<link rel="stylesheet" type="text/css" href="{% static 'css/list_produk.pengantaran.css' %}" />
<script src="https://kit.fontawesome.com/a076d05399.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src = "{% static 'create_list_produk_dibeli.js' %}"></script>
{% endblock %}

{% block title %}
<title>Create List Produk Dibeli</title>
{% endblock %}

{% block content %}
<h1>FORM CREATE LIST PRODUK DIBELI</h1>
{% if form or message %}
    <div class="alert alert-danger" role="alert">
        <ul>
        {% if form %}
            {% for field, errors in form.errors.items %}
                {% for error in errors %}
                    <li>{{ error }}</li>
                {% endfor %}
            {% endfor %}
        {% endif %}
        {% if message %}
            <li>{{ message }}</li>
        {% endif %}
        </ul>
    </div>
    {% endif %}
<div class="form">
    <form method="POST">
        {% csrf_token %}
        <div class="form-group">
            <label for="id_produk">ID Produk</label>
            <select name="id_produk" class="form-control" id="id_produk">
                {% for id_produk in list_id_produk %}
                <option value="{{ id_produk }}">{{ id_produk }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="form-group">
            <label for="id_apotek">ID Apotek</label>
            <select name="id_apotek" class="form-control" id="id_apotek">
                {% for id_apotek in list_id_apotek %}
                <option value="{{ id_apotek }}">{{ id_apotek }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="form-group">
            <label for="id_transaksi">ID Transaksi</label>
            <select name="id_transaksi" class="form-control" id="id_transaksi">
                {% for id_transaksi in list_id_transaksi %}
                <option value="{{ id_transaksi }}">{{ id_transaksi }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="form-group">
            <label for="jumlah">Jumlah</label>
            <input name="jumlah" type="number" class="form-control" id="jumlah" min="0" required>
        </div>

        <div class="buttonHolder">
            <input class="btn btn-primary" type="submit">
        </div>
    </form>
</div>
{% endblock %}

list_produk_pengantaran/templates/list_produk_pengantaran/create_pengantaran_farmasi.html
{% extends 'base_with_login.html' %}{% load static  %}

{% block cssJs %}
<link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous" />
<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<link rel="stylesheet" type="text/css" href="{% static 'css/list_produk.pengantaran.css' %}" />
<script src="https://kit.fontawesome.com/a076d05399.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
{% endblock %}

{% block title %}
<title>Create Pengantaran Farmasi</title>
{% endblock %}

{% block content %}
<h1>FORM CREATE PENGANTARAN FARMASI</h1>
{% if form or message %}
    <div class="alert alert-danger" role="alert">
        <ul>
        {% if form %}
            {% for field, errors in form.errors.items %}
                {% for error in errors %}
                    <li>{{ error }}</li>
                {% endfor %}
            {% endfor %}
        {% endif %}
        {% if message %}
            <li>{{ message }}</li>
        {% endif %}
        </ul>
    </div>
    {% endif %}
<div class="form">
    <form method="POST">
        {% csrf_token %}
        <div class="form-group">
            <label for="id_transaksi">ID Transaksi</label>
            <select name="id_transaksi" class="form-control" id="id_transaksi">
                {% for id_transaksi in list_id_transaksi %}
                <option value="{{ id_transaksi }}">{{ id_transaksi }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="form-group">
            <label for="waktu">Waktu</label>
            <input name="waktu" type="text" class="form-control" id="waktu" required>
        </div>
        <div class="form-group">
            <label for="biaya_kirim">Biaya Kirim</label>
            <input name="biaya_kirim" type="number" class="form-control" id="biaya_kirim" required>
        </div>

        <div class="buttonHolder">
            <input class="btn btn-primary" type="submit">
        </div>
    </form>
</div>

<script>
    $( function() {
      $( "#waktu" ).datepicker();
    } );
    </script>
{% endblock %}

list_produk_pengantaran/templates/list_produk_pengantaran/list_produk_dibeli.html
{% extends 'base_with_login.html' %}{% load static  %}

{% block cssJs %}
<link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous" />
<link rel="stylesheet" type="text/css" href="{% static 'css/list_produk.pengantaran.css' %}" />
<script src="https://kit.fontawesome.com/a076d05399.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
{% endblock %}

{% block title %}
<title>List Produk Dibeli</title>
{% endblock %}

{% block content %}
<div class="header">
    <h1>LIST PRODUK DIBELI</h1>
</div>
<table id="listProdukDibeliTable">
    <thead>
        <tr>
            <th>ID Produk</th>
            <th>ID Apotek</th>
            <th>ID Transaksi Pembelian</th>
            <th>Jumlah</th>
            {% if request.session.role == "ADMIN_APOTEK" %}
            <th>Action</th>
            {% endif %}
        </tr>
    </thead>
    <tbody>
        {% for data in content  %}
        <tr>
            <td>{{ data.id_produk }}</td>
            <td>{{ data.id_apotek }}</td>
            <td>{{ data.id_transaksi_pembelian }}</td>
            <td>{{ data.jumlah }}</td>
            {% if request.session.role == "ADMIN_APOTEK" %}
            <td><a class="btn btn-primary"
                    href="{% url 'list_produk_pengantaran:update_list_produk_dibeli' id_apotek=data.id_apotek id_produk=data.id_produk id_transaksi_pembelian=data.id_transaksi_pembelian %}"
                    role="button">Update</a>
                <a class="btn btn-danger"
                    href="{% url 'list_produk_pengantaran:delete_list_produk_dibeli' id_apotek=data.id_apotek id_produk=data.id_produk id_transaksi_pembelian=data.id_transaksi_pembelian %}"
                    role="button">Delete</a></td>
            {% endif %}
        </tr>
    </tbody>
    {% endfor %}
</table>

<!-- external js -->
<script src="{% static 'js/list_produk_dibeli.js' %}"></script>
{% endblock %}

list_produk_pengantaran/templates/list_produk_pengantaran/pengantaran_farmasi.html
{% extends 'base_with_login.html' %} {% load static %}{% block content %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <!-- Bootstrap CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/list_produk.pengantaran.css' %}" />

    <script src="https://kit.fontawesome.com/a076d05399.js"></script>

    <!-- Google jQuery CDN -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

    <title>Pengantaran Farmasi</title>
</head>

<body>
    <div class="header">
        <h1>PENGANTARAN FARMASI</h1>
    </div>
    <table id="pengantaranFarmasiTable">
        <thead>
            <tr>
                <th>ID Pengantaran</th>
                <th>ID Kurir</th>
                <th>ID Transaksi</th>
                <th>Waktu</th>
                <th>Status</th>
                <th>Biaya Kirim</th>
                <th>Total Biaya</th>
                {% if request.session.role == "ADMIN_APOTEK" %}
                <th>Action</th>
                {% endif %}
            </tr>
        </thead>
        <tbody>
            {% for data in content  %}
            <tr>
                <td>{{ data.id_pengantaran }}</td>
                <td>{{ data.id_kurir }}</td>
                <td>{{ data.id_transaksi_pembelian }}</td>
                <td>{{ data.waktu }}</td>
                <td>{{ data.status_pengantaran }}</td>
                <td>{{ data.biaya_kirim }}</td>
                <td>{{ data.total_biaya }}</td>
                {% if request.session.role == "ADMIN_APOTEK" %}
                <td><a class="btn btn-primary" href="{% url 'list_produk_pengantaran:update_pengantaran_farmasi' id=data.id_pengantaran %}"
                        role="button">Update</a>
                    <a class="btn btn-danger" href="{% url 'list_produk_pengantaran:delete_pengantaran_farmasi' id=data.id_pengantaran %}" role="button">Delete</a></td>
                {% endif %}
                </tr>
        </tbody>
        {% endfor %}
    </table>

    <!-- external js -->
    <script src="{% static 'js/list_produk_dibeli.js' %}"></script>
</body>

</html>
{% endblock %}

list_produk_pengantaran/templates/list_produk_pengantaran/update_list_produk_dibeli.html
{% extends 'base_with_login.html' %} {% load static %}{% block content %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <!-- Bootstrap CSS -->
  <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous" />
  <link rel="stylesheet" type="text/css" href="{% static 'css/list_produk.pengantaran.css' %}" />

  <script src="https://kit.fontawesome.com/a076d05399.js"></script>

  <!-- Google jQuery CDN -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>


  <title>Update List Produk Dibeli</title>
</head>

<body>
  <h1>FORM UPDATE LIST PRODUK DIBELI</h1>
  {% if form or message %}
    <div class="alert alert-danger" role="alert">
        <ul>
        {% if form %}
            {% for field, errors in form.errors.items %}
                {% for error in errors %}
                    <li>{{ error }}</li>
                {% endfor %}
            {% endfor %}
        {% endif %}
        {% if message %}
            <li>{{ message }}</li>
        {% endif %}
        </ul>
    </div>
    {% endif %}
  <div class="form">
    <form method="POST">
      {% csrf_token %}
      <div class="form-group">
        <label for="id_produk">ID Produk</label>
        <input name="id_produk" type="number" class="form-control" id="id_produk" placeholder="1" value="{{ data.id_produk }}" disabled>
      </div>
      <div class="form-group">
        <label for="id_apotek">ID Apotek</label>
        <input name="id_apotek" type="number" class="form-control" id="id_apotek" placeholder="1" value="{{ data.id_apotek }}" disabled>
      </div>
      <div class="form-group">
        <label for="id_transaksi_pembelian">ID Transaksi Pembelian</label>
        <select name="id_transaksi_pembelian" class="form-control" id="id_transaksi_pembelian">
          {% for id_transaksi_pembelian in list_id_transaksi_pembelian %}
          {% if id_transaksi_pembelian == data.id_transaksi_pembelian %}
          <option value="{{ id_transaksi_pembelian }}" selected>{{ id_transaksi_pembelian }}</option>
          {% else %}
          <option value="{{ id_transaksi_pembelian }}">{{ id_transaksi_pembelian }}</option>
          {% endif %}
          {% endfor %}
        </select>
      </div>
      <div class="form-group">
        <label for="jumlah">Jumlah</label>
        <input name="jumlah" type="number" class="form-control" min="0" id="jumlah" value="{{ data.jumlah }}">
      </div>
      <div class="buttonHolder">
        <button type="submit" class="btn btn-primary">Update</button>
      </div>
    </form>
  </div>
</body>

</html>
{% endblock %}